[tool.poetry]
name = "projeto-etl"
version = "0.1.0"
description = ""
authors = ["Maria Isabel <mipt1612@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
streamlit = "^1.32.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
